const express = require('express');
const cors = require('cors');

const app = express();
const PORT = process.env.PORT || 3000;

// Middleware
app.use(cors());
app.use(express.json());

// 🟢 Keep-Alive Route for cron-job.org (Bulletproofed)
app.get('/ping', (req, res) => {
  res.status(200).send(`Pong! Aether Backend is wide awake.`);
});

// 🔴 The Stealth Extraction Matrix (Agent Bypass Edition v11)
app.get('/api/rip', async (req, res) => {
  try {
    const videoUrl = req.query.url; 
    
    if (!videoUrl) {
      return res.status(400).send(`Extraction Matrix Error: No video URL provided.`);
    }

    // Call the root Cobalt endpoint with the updated parameters
    const response = await fetch('https://api.cobalt.tools/', {
      method: 'POST',
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
      },
      body: JSON.stringify({
        url: videoUrl,
        videoQuality: "720"
      })
    });

    if (!response.ok) {
      throw new Error(`Bypass API failed with status ${response.status}`);
    }

    const data = await response.json();

    // The API returns a status and a direct url link
    if (data && data.url) {
      return res.redirect(data.url);
    } else {
      throw new Error(`No download link generated by the bypass server.`);
    }

  } catch (error) {
    console.error('Extraction error:', error.message);
    res.status(500).send(`Extraction Matrix Failed: Could not bypass security. Error: ${error.message}`);
  }
});

// Start the server
app.listen(PORT, () => {
  console.log(`Aether Backend running on port ${PORT}`);
});
